with(x, plot(x$DateTime, x$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering"))
lines(x$DateTime, x$Sub_metering_1, type="l")
lines(x$DateTime, x$Sub_metering_2, type="l", col="red")
lines(x$DateTime, x$Sub_metering_3, type="l", col="blue")
legend("topright", pch="-", col= c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "plot3.png")
dev.off()