par(mfrow=c(2,2))
with(x, {
  plot(x$DateTime, x$Global_active_power, type="l", xlab="", ylab="Global Active Power")
  plot(x$DateTime, x$Voltage, type="l", xlab="datetime", ylab="Voltage")
  plot(x$DateTime, x$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
    lines(x$DateTime, x$Sub_metering_1, type="l")
    lines(x$DateTime, x$Sub_metering_2, type="l", col="red")
    lines(x$DateTime, x$Sub_metering_3, type="l", col="blue")
    legend("topright", pch="-", col= c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(x$DateTime, x$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
})